In the above-given dataframe, usernames are the display names of the learner's accounts shown on a video-conferencing app when taking classes.

The instructor clearly said to the learners that usernames must contain the real name (name) of the learners.

We tried to print the userid of the learners who haven't followed the instruction:

In [2]:
import pandas as pd

data = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(data)

def check(name,username):
    return name.lower() in username

In [5]:
df[~(df.apply(lambda x:check(x['name'],x['username']), axis=0))]['userid']

KeyError: 'name'

In [6]:
data = {'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]}

In [7]:
df = pd.DataFrame(data)

In [9]:
import pandas as pd



def replace_ages(a):
    '''a is a dataframe with columns ['name', 'age']
       Output A dataframe with same columns but with changed records as per required is expected to be returned'''

    # YOUR CODE GOES HERE

    def age_category(age):
        if age < 18:
            return 'kid'
        elif 18 <= age <= 50:
            return 'adult'
        else:
            return 'senior'

    # Apply the function to age column
    a['age'] = a['age'].apply(age_category)

    return a

print(df)

     name  age category
0     Ram   10      kid
1   Shyam   18    adult
2  Mukesh   60   senior
3  Suresh   50    adult

Given a dataframe containing records of student and their marks, and the cutoff marks k

Return the name of students who scored marks greater than or equal to the cuttof i.e. marks >= k

A DataFrame containing marks records
k (cutoff marks)
Output Format:
A Series

In [10]:
import pandas as pd

data = {
    'name': ['Luffy', 'Chopper', 'Zoro', 'Sanji'],
    'marks': [15, 89, 33, 32]
}

df = pd.DataFrame(data)


def filter(df, k):
    '''
    INPUT:
        df -> dataframe
        k -> cutoff (int)

    OUTPUT:
        result -> dataframe
    '''

    ### STEP 1 : Create mask
    mask = df['marks'] >= k

    ### STEP 2: Use mask to filter rows
    result = df[mask]['name']

    return result

In [11]:
filter(df,30)

1    Chopper
2       Zoro
3      Sanji
Name: name, dtype: object

In [12]:
import pandas as pd

data = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry'],
}

df = pd.DataFrame(data)

Given a dataframe df having the income details for different individuals.

Return a Series that contains the gender-wise average income.

Input Format: (NOTE: No need to take the input explicitly — the input-handling code is already in place.)

A DataFrame
Output Format:

A DataFrame

In [19]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)

def calc_income(df):
    '''
    INPUT: df -> dataframe

    OUTPUT: result -> dataframe
    '''

    result = df.groupby('gender')['income'].mean()

    return pd.DataFrameresult

In [18]:
calc_income(df)

gender
F    36000.0
M    39000.0
Name: income, dtype: float64

Given a dataframe containing student's marks for multiple subjects,

Return a dataframe which contains records of subject-wise highest marks along with their roll number.

Input Format:

A DataFrame
Output Format:

A DataFrame

In [20]:
import pandas as pd

def get_marks(df):
    '''
    INPUT: df -> dataframe

    OUTPUT: result -> dataframe
    '''

    ### STEP 1: group the df using subject and get max marks
    max_marks = df.groupby('subject')['marks'].max()

    ### STEP 2: reset the index
    max_marks = max_marks.reset_index()

    ### STEP 3: merge with original df to get roll id
    result = pd.merge(df, max_marks, on=['subject','marks'])

    return result

Given a dataframe containing records of some college students, with columns "Name", "Age", "Percentage" and "Stream".

Return the name of the students belonging to either Commerce or Arts Stream and with a Percentage greater than or equal to 75.

Input Format:
First line of the input contains the dataframe, in the form of a dictionary.

Output Format:
The selected student names in a Series.

In [20]:
import pandas as pd

data = {
    'Name': ['Himanshu', 'Robert', 'Karie', 'Rohan', 'John'],
    'Age': [15, 14, 15, 16, 17],
    'Percentage': [80, 77, 83, 45, 70],
    'Stream': ['Commerce', 'Science', 'Arts', 'Commerce', 'Science']
}

df = pd.DataFrame(data)